name: Publish JavaScript to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build WASM
        working-directory: core
        run: wasm-pack build --target nodejs --out-dir pkg --out-name enhex-core

      - name: Copy WASM & meta files
        working-directory: bindings/js
        run: node scripts/copy-wasm.js

      - name: Setup npn CI
        run: npm ci

      - name: Build JS Binding
        run: npm run build --if-present

      - name: Test JS Package
        run: npm test

      - name: Publish to npm
        working-directory: bindings/js
        run: npm publish
